# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22a55885c1bc0e000bba6c0d0bc89f2b2e1f4a4e948b32d86123bfe8319050557797145fee5ce856ee6fece6aae0c8b1cc8cbe10260fd459b7bebf86103e147

test:
  secret_key_base: e6d988201698d64b1b11962c7eefafaabc991ab7685f4c0e5bf2f84224a705e8fd9c7c405cbe6bc14f16844790f6e3a94ecd1f0e56abb0d9ef67830b4c1b5794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
